### ISSUE TITLE
/usr/bin/metview_bin/metview_help is not executable

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/Metview-rpm#1]
```
$ metview -h
/usr/bin/metview: riga 1037: /usr/bin/metview_bin/metview_help: Permesso negato
metview: EXIT on ERROR (line 1), exit status 126, starting 'cleanup'
```
adding executable permissions to `metview_help` solves the problem

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
