### ISSUE TITLE
xorg-x11-utils should be a dependency

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/Metview-rpm#2]
```
$ metview -h
/usr/bin/metview: riga 940: xdpyinfo: comando non trovato
```

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
